### ISSUE TITLE
Assume role expired less than 2 hours

### ISSUE THREAD

**Issue by marryblossom** [realestate-com-au/stackup#33]
Since our stack creation would run at least last 2h 30m, we are now using `--with-role` to extend the assumed role credential,  but it looks like the assumed role still expired in 2 hours.

Here is part of log:
21-Nov-2016 21:44:53: start to create the stack;
21-Nov-2016 23:35:02	ERROR: The security token included in the request is expired
21-Nov-2016 23:35:02	An error occurred (ExpiredToken) when calling the DescribeStacks operation: The security token included in the request is expired

**Comment by mdub** [comment]
I must admit that, while I've tested that `--with-role` can assume roles, I haven't tested the auto-renewal.  Rather, I've assumed [the documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/AssumeRoleCredentials.html) was true. Thank you for testing it :-)

Are you running this on an EC2 instance with a instance-profile?  Or, from you laptop?

**Comment by mdub** [comment]
Bear in mind that, when using `--with-role`, you still need sufficient credentials to _renew_ the temporary credentials obtained from STS, when they expire.  So, you need to _start_ with long-lived or renewable credentials.

Typical use-case is:
- run Stackup on an EC2 instance with a suitable instance-profile
  - use `--with-role` to specify an alternate role
- Stackup obtains credentials via the instance-profile, and use them to to assume a role and obtain STS credentials
- time passes; STS credentials expire
- (again) Stackup obtains credentials via the instance-profile, and use them to to assume a role and obtain STS credentials
- ... etc ...

**Comment by marryblossom** [comment]
We are using Bamboo agent in EC2 to run stack creation, so the long-lived or renewable credentials should be there.

**Comment by mdub** [comment]
@marryblossom: Investigating with Linh Pham, it appears your scripts are assuming a role with STS, and setting `AWS_ACCESS_KEY_ID` etc, even _before_ `stackup` is invoked.  So, Stackup ends up using those explicitly-provided credentials, rather than obtaining some via the agent's instance-profile. Later, when the temporary credentials obtained by Stackup expire, it can't renew them.

The fix is to ensure that "AWS_xxx" environment variables are _not_ set, when `stackup` is invoked.
