### ISSUE TITLE
rake tasks - some params from ENV 

### ISSUE THREAD

**Issue by brettswift** [realestate-com-au/stackup#36]
I just started poking around at this gem.  Looks interesting. 

I can't seem to figure out how I can get some params into environment variables.   

```
  t.stack = "NetworkPipeline"
  t.template = "pipelines/networkPipeline.yaml"
  t.parameters = "pipelines/networkPipelineConfig.yaml"
  t.tags = {
    "builtby" => `whoami`
  }
```

in the param file, I don't want to have my GitHub access token.  Is there a way to inject this?

Is there a way to do this if I was to write a ruby script instead of the rake task? 

I am poking around at some of the cli - just a bit of friendly feedback as well - the subtasks don't have documentation on the command line so it's a little tricky  - and there aren't examples of using the CLI in the examples folder so I have to go digging around in the code.

**Comment by mdub** [comment]
Hi @brettswift.

Using the Rake tasks, parameters (like tags) can be specified either via a file, or as data.  Here's an example of the later:

    Stackup::RakeTasks.new("pipeline") do |t|
      t.template = "pipelines/networkPipeline.yaml"
      t.parameters = {
        "Ami" => "ami-12345678",
        "GitHubAccessToken" => ENV.fetch("GITHUB_TOKEN")
      }
    end

You'll certainly get a lot more flexibility invoking [`Stackup.stack(name).up`](http://www.rubydoc.info/gems/stackup/Stackup%2FStack:create_or_update) directly, though.

A word of warning: be careful about passing "secrets" as CloudFormation stack parameters, because they'll be available (in plaintext) via the CloudFormation API.  At REA, we prefer to pass such secrets around in KMS-encrypted form, and later decrypt them in our applications (or Docker containers) - we use a little tool called [`shush`](https://github.com/realestate-com-au/shush) for that.

Sorry that you're finding the CLI difficult to navigate. Do you have suggestions on making it easier? The main sub-commands are documented in the README.  You can get a list of subcommands using `stackup --help`, and help on a particular subcommand using `stackup NAME COMMAND --help`.

**Comment by brettswift** [comment]
Thanks @mdub 

So I guess I won't be able to use the rake task, as it won't support environment variables going in as template parameters.

I'm just working on a POC - eventually I'll not need my GitHub token, but rather use a policy from CodeCommit or something.

The CLI docs are good at the root (`stackup --help`)  but subcommands would be a nice add.  ie: `stackup up --help`.   However I think I have better luck with a little ruby script as you mentioned. 

Thanks!

**Comment by mdub** [comment]
> I guess I won't be able to use the rake task, as it won't support environment variables going in as template parameters

Uh, you can specify template parameters as (Ruby) code, enabling use of environment variables. See the example in my [comment](#issuecomment-279109360), above.

> The CLI docs are good at the root (stackup --help) but subcommands would be a nice add. ie: stackup up --help.

Subcommand help is already available. I mentioned this above, too.  Here's a example:

```
$ stackup blah up --help
Usage:
    stackup NAME up [OPTIONS]

Options:
    -t, --template FILE           template file
    -T, --use-previous-template   reuse the existing template
    -p, --parameters FILE         parameters file (last wins)
    -o, --override PARAM=VALUE    parameter overrides
    --tags FILE                   stack tags file
    --policy FILE                 stack policy file
    --on-failure ACTION           when stack creation fails: DO_NOTHING, ROLLBACK, or DELETE (default: "ROLLBACK")
    -L, --list                    list stacks
    -Y, --yaml                    output data in YAML format
    --region REGION               set region
    --with-role ROLE_ARN          assume this role
    --retry-limit N               maximum number of retries for API calls (default: $AWS_API_RETRY_LIMIT)
    --[no-]wait                   wait for stack updates to complete (default: true)
    --wait-poll-interval N        polling interval while waiting for updates (default: 5)
    --debug                       enable debugging
    --version                     display version
    -h, --help                    print help
```
