### ISSUE TITLE
Why does stackup transform YAML templates into JSON before uploading?

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/stackup#74]
I've been informed that stackup transforms your YAML templates into JSON before uploading to CloudFormation.

Is this true?

This feels like suprising and unnecessary behaviour? 

What's the purpose? Does StackUp depend on this for any functionality?

**Comment by tigris** [comment]
> stackup transforms your YAML templates into JSON before uploading to CloudFormation. Is this true?

Yes. As per https://github.com/realestate-com-au/stackup/blob/dd0775994baa5c11e103209aa5cff5554997ec23/README.md#yaml-support

> This feels like suprising and unnecessary behaviour?

Please see previous discussion: https://github.com/realestate-com-au/stackup/issues/31

> What's the purpose?

I believe the original purpose was that AWS didn't support YAML at all, stackup did support YAML, so the only course of action was to translate it.

> Does StackUp depend on this for any functionality?

Yes and no. See above about previous discussion. It'd require a lot of changes to the structure of the code, the feature set of stackup would change slightly.

I'll close this for now as it seems like you were just after more info for now? If we want to discuss further, we can open a feature request describing expected behaviour and test cases.

**Comment by ps-jay** [comment]
> I've been informed that stackup transforms your YAML templates into JSON before uploading to CloudFormation.
> 
> Is this true?

Not strictly any more.
Implemented as `--preserve-template-formatting` in #86
